server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: danilanovikov
    password: demo2228
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  keycloak:
    url: http://localhost:9080
    token-url: http://localhost:9080/realms/OnlineLibrary/protocol/openid-connect/token
    realm: OnlineLibrary
    client:
      id: library-keycloak-client
      secret: Bm4WXOYmlxbeBk3ZTBaKufYkfhCiC0lb

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/OnlineLibrary
          jwk-set-uri: http://localhost:9080/realms/OnlineLibrary/protocol/openid-connect/certs
integration:


