version: "3.8"

services:
  postgres-keycloak:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=danilanovikov
      - POSTGRES_PASSWORD=demo2228
    ports:
      - "5432:5432"

  keycloak:
    image: bitnami/keycloak:22.0.5
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=postgres-keycloak
      - KEYCLOAK_DATABASE_NAME=postgres
      - KEYCLOAK_DATABASE_USER=danilanovikov
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_DATABASE_PASSWORD=demo2228
    ports:
      - "9080:8080"
    depends_on:
      - postgres-keycloak
  redis:
    image: redis:7.4.0
    restart: "on-failure"
    ports:
      - "6379:6379"